### ISSUE TITLE
Add a contact button or configure a password reset system.

### ISSUE THREAD

**Issue by sirbaratusii** [ziplantil/DescentMissionArchive#16]
Hello, I lost my password for my account "THEBaratusII" and went on the attempt to reset my password only to find out that _"E-mail is not configured on this server. Please contact the server administrator for assistance."_

A system to reset passwords or even a contact button would be best appreciated. Thanks!

**Comment by ziplantil** [comment]
The DXMA application does have this feature in its source code - but it has not been configured on the server (I assume this is sectorgame's DXMA we are talking about).

**Comment by sirbaratusii** [comment]
> The DXMA application does have this feature in its source code - but it has not been configured on the server (I assume this is sectorgame's DXMA we are talking about).

Yes. Though they did add it in. I am not sure when because I haven't checked the site in months until now. I think it should be good now.
